// frontend/src/pages/Item/CreateItem.tsx
import { useParams, Navigate } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useGetInventoryQuery, useGenerateCustomIdQuery } from '@/features/inventory/inventoryApi'
import ItemForm from '@/components/items/ItemForm'
import LoadingSpinner from '@/components/common/LoadingSpinner'
import { useEffect, useState } from 'react'

export default function CreateItem() {
  const { id: inventoryId } = useParams<{ id: string }>()
  const { data: inventory, isLoading: inventoryLoading, error } = useGetInventoryQuery(inventoryId!)
  const { data: customIdData, refetch: generateCustomId } = useGenerateCustomIdQuery(inventoryId!, {
    skip: !inventoryId
  })
  const [autoGeneratedId, setAutoGeneratedId] = useState<string>('')

  // Update auto-generated ID when data changes
  useEffect(() => {
    if(customIdData?.customId) {
      setAutoGeneratedId(customIdData.customId)
    }
  }, [customIdData])

  if (inventoryLoading) {
    return (
      <div className="flex justify-center py-12">
        <LoadingSpinner size="lg" />
      </div>
    )
  }

  if (error || !inventory) {
    return <Navigate to="/dashboard" replace />
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="space-y-2">
        <Link
          to={`/inventory/${inventory.id}`}
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Inventory
        </Link>
        <h1 className="text-3xl font-bold tracking-tight">Add New Item</h1>
        <p className="text-muted-foreground">
          Add a new item to {inventory.title}
        </p>
        
        {/* Auto-generated ID Info */}
        {inventory.customIdFormat && autoGeneratedId && (
          <div className="rounded-lg bg-blue-50 dark:bg-blue-950 p-3">
            <p className="text-sm text-blue-800 dark:text-blue-200">
              <strong>Custom ID will be auto-generated:</strong>{' '}
              <code className="font-mono bg-blue-100 dark:bg-blue-900 px-1 rounded">
                {autoGeneratedId}
              </code>
            </p>
          </div>
        )}
      </div>

      {/* Form */}
      <ItemForm 
        inventory={inventory} 
        initialCustomId={autoGeneratedId}
        generateCustomId={generateCustomId}
      />
    </div>
  )
}